//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crafty
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CraftyDBEntities : DbContext
    {
        public CraftyDBEntities()
            : base("name=CraftyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Extract> Extracts { get; set; }
        public virtual DbSet<Grain> Grains { get; set; }
        public virtual DbSet<Hop> Hops { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<RecipeType> RecipeTypes { get; set; }
        public virtual DbSet<Style> Styles { get; set; }
        public virtual DbSet<Water> Waters { get; set; }
        public virtual DbSet<Yeast> Yeasts { get; set; }
    }
}
