//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crafty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grain
    {
        public Grain()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int GrainId { get; set; }
        public string GrainName { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
