//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crafty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int RecipeId { get; set; }
        public string RecipeName { get; set; }
        public string Brewer { get; set; }
        public Nullable<int> StyleId { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public Nullable<int> RecipeTypeId { get; set; }
        public Nullable<int> GrainId { get; set; }
        public Nullable<int> HopsId { get; set; }
        public string Misc { get; set; }
        public Nullable<int> YeastId { get; set; }
        public Nullable<int> WaterId { get; set; }
        public Nullable<int> ExtractId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Extract Extract { get; set; }
        public virtual Grain Grain { get; set; }
        public virtual Hop Hop { get; set; }
        public virtual RecipeType RecipeType { get; set; }
        public virtual Style Style { get; set; }
        public virtual Water Water { get; set; }
        public virtual Yeast Yeast { get; set; }
    }
}
